name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 mypy

      - name: Format check (Black)
        run: black --check .

      - name: Lint (Flake8)
        run: flake8

      - name: Type check (mypy)
        run: mypy .

      - name: Run tests
        run: pytest --maxfail=1 -q
